export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const GET_PRODUCTS = "GET_PRODUCTS"
export const POPULATE_INITIAL_PRODUCTS = "POPULATE_INITIAL_PRODUCTS"